#!/bin/sh

#
# Executes the given tests.
#
# Run `./test \*` to run all tests.
#
# Returns the number of failed tests.
#

dir="${0%${0##*/}}"
cd "${dir%/}/tests" || return 1

# Inject into bash, because LINENO in `bash -c` is off by one
nl='
'

fails=0
for test in $@; do
	# Inject bsda:test and add `|| bsda:test:err $LINENO` to every line
	code="bsda_dir='../src';readonly bsda_dir;. ../src/bsda_test.sh;$(
		awk -f../src/testify.awk "$test")" || return 1
	echo "Running: sh $test"
	if sh -c "$code"; then
		echo "Passed: sh $test"
	else
		echo "Failed: sh $test"
		fails=$((fails + 1))
	fi
	which bash >&- || continue
	echo "Running: bash $test"
	if bash -c "$nl$code"; then
		echo "Passed: bash $test"
	else
		echo "Failed: bash $test"
		fails=$((fails + 1))
	fi
done
if [ $fails -ne 0 ]; then
	echo "Test runs failed: $fails"
fi
return $fails
