#!/bin/sh

#
# Executes the given tests.
#
# Glob patterns are matched against the tests in `tests/`.
#
# Execute without arguments to run all tests or list specific tests.
#
# Returns the number of failed tests.
#

set -e

dir="${0%${0##*/}}"
dir="${dir%/}"
cd "${dir:-.}/tests" || return 1

# Match all tests when no arguments are given
if [ $# -eq 0 ]; then
	set -- *
fi

fails=0
for test in $@; do
	# Remove folder component
	test="${test##*/}"

	# Skip hidden files, `.` and `..`
	if [ -z "${test##.*}" ]; then
		echo "${test} failed: skipping"
		fails=$((fails + 1))
		continue
	fi

	# Need to exist, needs read access
	if [ ! -r "$test" ]; then
		echo "${test} failed: cannot access"
		fails=$((fails + 1))
		continue
	fi

	# Inject bsda:test and add `|| bsda:test:err $LINENO` to every line
	code="bsda_dir='../src';readonly bsda_dir;. ../src/bsda_test.sh;$(
		awk -f../src/testify.awk "$test")" || return 1
	for shell in sh bash; do
		which $shell >&- || continue
		echo "${test} running: ${shell} ${test}"
		if $shell -c "$code"; then
			echo "${test} passed:  ${shell} ${test}"
		else
			echo "${test} failed:  ${shell} ${test}"
			fails=$((fails + 1))
		fi
	done
done
if [ $fails -ne 0 ]; then
	echo "Test runs failed: $fails"
fi
exit $fails
