#!/bin/sh
set -f
prefix="${0##*/}"
namespace="$(echo "$prefix" | /usr/bin/tr '_' ':')"

bsda_dir="%%DATADIR%%"
#HACK
bsda_dir="${0%${0##*/}}";bsda_dir="${bsda_dir%/}"
#hack
readonly bsda_dir

. ${bsda_dir:-.}/${prefix}.sh
${namespace}:Session session "$@"
